# YML for automating issue movement due to PR creation
name: PR Creation

on:
  pull_request:
    types: [opened, edited, ready_for_review, synchronize]

jobs:
  move-linked-issues:
    runs-on: ubuntu-latest
    name: Move linked issues to In Review column
    steps:
     - name: Get linked issues of a PR
       env:
        GH_TOKEN: ${{ secrets.YOUR_ACCESS_TOKEN }}
        USER: kcw36
        PROJECT_NUMBER: 1
        PR_ID: ${{ github.event.pull_request.node_id }}
       run: |
        linked_issue_id="$( gh api graphql -f query='
        query($pr:ID!) {
          node(id: $pr) {
            ... on PullRequest {
              closingIssuesReferences(first:1, userLinkedOnly:false) {
                totalCount
                nodes { 
                  id 
                  projectItems(first: 5) {
                    nodes {
                      id
                    }
                  }
                }
              }
            }
          }
        }' -f pr=$PR_ID --jq '.data.node.closingIssuesReferences.nodes[0].projectItems.nodes[0].id')"
        echo "ISSUE ID:"
        echo "$linked_issue_id"
        echo "PR_ID:"
        echo "${{env.PR_ID}}"
        echo "LINKED_ISSUE_ID=$linked_issue_id" >> $GITHUB_ENV
     - name: Change status to "Being Worked On"
       env:
        GH_TOKEN: ${{ secrets.YOUR_ACCESS_TOKEN }}
        PROJECT_ID: PVT_kwHOBpjqoc4A6fB5
        ISSUE_ID: ${{ env.LINKED_ISSUE_ID }}
        STATUS_FIELD_ID: PVTSSF_lAHOBpjqoc4A6fB5zgvEHBM
        BEING_WORKED_ON_OPTION_ID: df73e18b
       run: |
        updatedAt="$( gh api graphql -f query='
        mutation($issueId:ID!, $projectId:ID!) {
          updateProjectV2ItemFieldValue(input: {projectId: $projectId, fieldId: "${{env.STATUS_FIELD_ID}}", itemId: $issueId, value: {singleSelectOptionId: "${{env.BEING_WORKED_ON_OPTION_ID}}"}}) {
            projectV2Item {
              type
              updatedAt
            }
          }
        }' -f issueId=$ISSUE_ID -f projectId=$PROJECT_ID  --jq '.data.updateProjectV2ItemFieldValue.projectV2Item.updatedAt')"